### ISSUE TITLE
[please fix] modstats crashing with twilight forest

### ISSUE THREAD

**Issue by iamweirdie** [ldtteam/modstats#1]
Player Wither_gy7 aka Discord User jtapusen#0767 was running around when he crashed.
**To Reproduce**
1. Enter the area directed in the crash log - 1361.83, 220.22, -479.06
2. Crash

**Versions:**

 - Minecraft: 1.12.2
 - Forge: 14.23.5.2838 
 - Mod Pack : Edge of Twilight 1.8.9 
https://www.curseforge.com/minecraft/modpacks/edge-of-twilight/files/2760811

Crash Report: https://paste.dimdev.org/netimayaku.rb

**Additional context**
Player reported that the urGhast was extremely laggy in SSP
Meanwhile in the Twilight Forest Discord...
![image](https://user-images.githubusercontent.com/34356883/62920209-e5674480-bd59-11e9-9bd8-30acfaeb9d03.png)
^Discord Username Androsa#5414^

**Comment by Raycoms** [comment]
Fix uploaded to curse
